### ISSUE TITLE
Project Notes.

### ISSUE THREAD

**Issue by joshmanders** [joshmanders/node-by-example#2]
Some notes about the project and how we plan on doing things.

- [x] Link to docs anytime you can to further the reader's knowledge of the stuff used.
- [x] Emphasis keeping docs up to date with best practices and standards.
- [x] Style guide, **CONSERVATIVE** on standards. **ENFORCE** semicolons. This is for newbies *not* veterans.
- [x] Write `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md` outlining how to submit an issue or pull request.
- [x] Write `CONTRIBUTING.md`
- [x] Establish a Code of Conduct
